[package]
name = "shuttle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
dotenvy = "0.15.7"
pavex = "0.1.74"
server = { path = "../server" }
server_sdk = { path = "../server_sdk" }
shuttle-runtime = { version = "0.52.0", default-features = false }
tracing = "0.1.41"